<a href="https://colab.research.google.com/github/Yeunseok97/Data-analysis_machin_learning/blob/main/Numpy_review_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### numpy 학습
- 배열과 리스트의 차이
- 배열생성 및 다루는 기법
- 기술통계함수
- 결과에 대한 분석방법

### Array
- 모든 원소가 같은 자료형이어야됨.
- 원소의 갯수를 바꿀 수 없음
- 배열의 차원, 크기, 타입(ndim, shape, dtype)
 


In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
def aryinfo(ary):
  print("type", type(ary))
  print("shape", ary.shape)
  print("dimension -", ary.ndim)
  print("dtype",ary.dtype)
  print()
  print("data -\n", ary)


In [3]:
oneAry = np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(oneAry)

type <class 'numpy.ndarray'>
shape (10,)
dimension - 1
dtype int64

data -
 [0 1 2 3 4 5 6 7 8 9]


#### 벡터화연산 vectorized operation
- 각 원소에 대한 반복연산을 하나의 명령어로 처리한 것
- 비교, 산술, 논리연산을 포함하는 모든 수학연산에 적용됨.

In [4]:
data = [1,2,3,4,5,6,7,8]
data *2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
data = [1,2,3,4,5,6,7,8]
result = []

for d in data:
  result.append(d*2)

print(result)

[2, 4, 6, 8, 10, 12, 14, 16]


In [6]:
result2 = [d*2 for d in data]
print(result2)

[2, 4, 6, 8, 10, 12, 14, 16]


In [7]:
result3 = oneAry * 2
print(result3)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
data01 = [1,2,3,4,5]
data02 = [10,20,30,40,50]

print(type(data01), type(data02))

<class 'list'> <class 'list'>


- array()함수를 이용해서 시퀀형을 넘파이의 배열로 타입을 변경할 수 있다.

In [9]:
xAry = np.array(data01)
yAry = np.array(data02)

print(type(xAry), type(yAry))


<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [10]:
# array 산술연산
aryinfo(xAry + yAry)
print()
aryinfo(xAry * yAry)
print()
aryinfo(2 * xAry + yAry)

type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype int64

data -
 [11 22 33 44 55]

type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype int64

data -
 [ 10  40  90 160 250]

type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype int64

data -
 [12 24 36 48 60]


In [11]:
print("비교 연산 - boolean masking")

print(xAry ==2)
print()
aryinfo(xAry ==2)

비교 연산 - boolean masking
[False  True False False False]

type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype bool

data -
 [False  True False False False]


In [12]:
print("비교연산 - boolean masking")

print(yAry > 10)
print()
aryinfo(yAry >10)

비교연산 - boolean masking
[False  True  True  True  True]

type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype bool

data -
 [False  True  True  True  True]


In [13]:
print('논리 연산 - ')

print((xAry == 2) | (yAry > 10))

논리 연산 - 
[False  True  True  True  True]


2차원 배열
- N dimensional Array
- 행렬
- list of list
- list of list of list

In [14]:
print("2개의 행과 3개의 열을 갖는 배열을 만든다면?")
twoAry = np.array([[1,2,3,],[4,5,6]], dtype = np.float64)
aryinfo(twoAry)

print()
print()
print("len() -")
print("len() 행의 갯수 - ", len(twoAry))
print("len() 행의 요소의 갯수, 즉 열을 의미한다 - ", len(twoAry[0]))
print("len() 행의 요소의 갯수, 즉 열을 의미한다 -", len(twoAry[1]))

2개의 행과 3개의 열을 갖는 배열을 만든다면?
type <class 'numpy.ndarray'>
shape (2, 3)
dimension - 2
dtype float64

data -
 [[1. 2. 3.]
 [4. 5. 6.]]


len() -
len() 행의 갯수 -  2
len() 행의 요소의 갯수, 즉 열을 의미한다 -  3
len() 행의 요소의 갯수, 즉 열을 의미한다 - 3


In [15]:
print('3차원 - 3 * 4 2개의 레이어 - ')
threeAry = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

print()
aryinfo(threeAry)

print()
print("len() -depth", len(threeAry))
print('len() - ' , len(threeAry[0]))
print('len() - ' , len(threeAry[1]))
print('row col - ' , len(threeAry[0][0])) 




3차원 - 3 * 4 2개의 레이어 - 

type <class 'numpy.ndarray'>
shape (2, 3, 4)
dimension - 3
dtype int64

data -
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

len() -depth 2
len() -  3
len() -  3
row col -  4


- 요소의 타입을 변경할 때 사용하는 함수.astype()

In [16]:
typeChange = threeAry.astype(np.float64)
aryinfo(typeChange)

type <class 'numpy.ndarray'>
shape (2, 3, 4)
dimension - 3
dtype float64

data -
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


- 배열도 인덱싱과 슬라이싱이 가능하다.

In [17]:
idxAry = np.array([1,2,3,4,5,6,7,8,9])
aryinfo(idxAry)

type <class 'numpy.ndarray'>
shape (9,)
dimension - 1
dtype int64

data -
 [1 2 3 4 5 6 7 8 9]


In [18]:
print("indexing")
print(idxAry[0])
print(idxAry[1])


indexing
1
2


In [19]:
aryinfo(twoAry)

type <class 'numpy.ndarray'>
shape (2, 3)
dimension - 2
dtype float64

data -
 [[1. 2. 3.]
 [4. 5. 6.]]


In [24]:
print('첫번째 행의 첫번째 열의 값 - ') 
print(twoAry[0 , 0])

print()
print('마지막 행의 마지막 열 - ')
print(twoAry[-1, -1])

print()
print('첫번째 행의 전체 - ')
print(twoAry[0, : ])

print()
print('첫번째 행의 두번째부터 끝까지 - ')
print(twoAry[0 , 1 : ])


print()
print('행이 아닌 y 축의 값을 구할 때 - ')
print(twoAry[ : , 1])



첫번째 행의 첫번째 열의 값 - 
1.0

마지막 행의 마지막 열 - 
6.0

첫번째 행의 전체 - 
[1. 2. 3.]

첫번째 행의 두번째부터 끝까지 - 
[2. 3.]

행이 아닌 y 축의 값을 구할 때 - 
[2. 5.]


In [25]:
matrixAry = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
aryinfo(matrixAry)

type <class 'numpy.ndarray'>
shape (3, 5)
dimension - 2
dtype int64

data -
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
'''
요구사항 구현 [실습] - 
이 행렬에서 값 7 을 인덱싱한다.
이 행렬에서 값 14 을 인덱싱한다.
이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
'''

In [36]:
print(matrixAry[1,2])
print()
print(matrixAry[-1,-1], matrixAry[2,4])
print()
print(matrixAry[1,1:3])
print()
print(matrixAry[1:,2])
print()
print(matrixAry[0:2,3:])

7

14 14

[6 7]

[ 7 12]

[[3 4]
 [8 9]]


#### fancy indexing
- boolean indexing
- 정수배열 indexing


In [37]:
ary = np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(ary)

type <class 'numpy.ndarray'>
shape (10,)
dimension - 1
dtype int64

data -
 [0 1 2 3 4 5 6 7 8 9]


In [41]:
print("짝수의 원소를 골라내고싶다면?")
idx = np.array([True, False, True, False, True, False, True, False, True, False])
print(ary[idx]) #짝수 인덱스에 트루값을 줘서 확인함

print()
print(ary[ary%2 == 0])

print("정수배열 인덱싱으로 구현한다면")

oddidx = np.array([1,3,5,7,9])
evenidx = np.array([0,2,4,6,8])

print()

print(ary[oddidx])
print(ary[evenidx])


짝수의 원소를 골라내고싶다면?
[0 2 4 6 8]

[0 2 4 6 8]
정수배열 인덱싱으로 구현한다면

[1 3 5 7 9]
[0 2 4 6 8]


In [42]:
ary % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [49]:
ary = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
aryinfo(ary)

print()
print("3의 배수를 출력", ary[ary%3==0])
print("4로 나누면 1이 남는 수를 출력", ary[ary%4 ==1])
print("3의배수이고 4로 나누면 1이 남는 수를 출력", ary[(ary%4 ==1) & (ary%3 ==0)])


type <class 'numpy.ndarray'>
shape (20,)
dimension - 1
dtype int64

data -
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

3의 배수를 출력 [ 3  6  9 12 15 18]
4로 나누면 1이 남는 수를 출력 [ 1  5  9 13 17]
3의배수이고 4로 나누면 1이 남는 수를 출력 [9]


- dtype 지정할 자료형은 접두어
- np.float54 -> f
- np.int32 -> i
- 문자열 U


In [50]:
ary = np.array([1,2,3], dtype="i")
aryinfo(ary)

type <class 'numpy.ndarray'>
shape (3,)
dimension - 1
dtype int32

data -
 [1 2 3]


- arange()

In [51]:
ary = np.arange(0,12,1).reshape(3,4)
aryinfo(ary)

type <class 'numpy.ndarray'>
shape (3, 4)
dimension - 2
dtype int64

data -
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
'''
아래 결과를 출력하도록 실습

indxing :  10
slicing : [6]
slicing : [[5]]
fancy indexing : [2 10] 
fancy indexing : [[2] [10] ]
fancy indexing : [[0 2] [4 6] [8 10] ]
'''

In [63]:
print("indexing : ", ary[2,2])
print("slicing :",ary[1:2,2])
print("slicing :",ary[1:2,1:2])

idx = [0,2]
print("fancy indexing", ary[idx,2])
print("fancy indexing", ary[idx,2:3])
print("fancy indexing", ary[:,idx])



indexing :  10
slicing : [6]
slicing : [[5]]
fancy indexing [ 2 10]
fancy indexing [[ 2]
 [10]]
fancy indexing [[ 0  2]
 [ 4  6]
 [ 8 10]]


#### 배열 생성 함수
- array()
- zeros(), ones(), zeros_like(), ones_like(), empty(), arange(), linspace(), logspace()

In [67]:
print("1차원")
zeroary = np.zeros(5, dtype="i")
aryinfo(zeroary)

print()
print("2차원")
zeroary = np.zeros((3,4), dtype="i")
aryinfo(zeroary)

print("3차원")
zeroary = np.zeros((3,3,4), dtype= "i")
aryinfo(zeroary)

1차원
type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype int32

data -
 [0 0 0 0 0]

2차원
type <class 'numpy.ndarray'>
shape (3, 4)
dimension - 2
dtype int32

data -
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
3차원
type <class 'numpy.ndarray'>
shape (3, 3, 4)
dimension - 3
dtype int32

data -
 [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [69]:
ary = np.zeros(5, dtype="<U4")
aryinfo(ary)

type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype <U4

data -
 ['' '' '' '' '']


In [70]:
ary[0] = "abc"
ary[1] = "oys"
ary[2] = "abcd"


In [71]:
ary

array(['abc', 'oys', 'abcd', '', ''], dtype='<U4')

In [72]:
print("1차원")
oneary = np.ones(5, dtype="i")
aryinfo(oneary)

1차원
type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype int32

data -
 [1 1 1 1 1]


In [74]:
print("1차원 -")
oneary = np.ones(5, dtype="U")
aryinfo(oneary)
print()

print("2차원")
oneary = np.ones((3,4), dtype ="i")
aryinfo(oneary)

print("3차원")
oneary = np.ones((3,3,4),dtype = "i")
aryinfo(oneary)

1차원 -
type <class 'numpy.ndarray'>
shape (5,)
dimension - 1
dtype <U1

data -
 ['1' '1' '1' '1' '1']

2차원
type <class 'numpy.ndarray'>
shape (3, 4)
dimension - 2
dtype int32

data -
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
3차원
type <class 'numpy.ndarray'>
shape (3, 3, 4)
dimension - 3
dtype int32

data -
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [76]:
o_likeary = np.ones_like(oneary, dtype ="U")
aryinfo(o_likeary)

type <class 'numpy.ndarray'>
shape (3, 3, 4)
dimension - 3
dtype <U1

data -
 [[['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]]


In [77]:
emptyary = np.empty((4,3))
aryinfo(emptyary)

type <class 'numpy.ndarray'>
shape (4, 3)
dimension - 2
dtype float64

data -
 [[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323 4.0e-323]
 [4.4e-323 4.9e-323 5.4e-323]]


In [78]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [80]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [83]:
np.arange(0,10,1).reshape(5,2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- 전치행렬 ->transpose matrix 행렬의 행은 열로, 열은 행으로 바꿔주는 행렬

In [88]:
ary = np.array([[1,2,3],[4,5,6]])
aryinfo(ary)

type <class 'numpy.ndarray'>
shape (2, 3)
dimension - 2
dtype int64

data -
 [[1 2 3]
 [4 5 6]]


In [90]:
ary = np.arange(1,7).reshape(2,3)
aryinfo(ary)

type <class 'numpy.ndarray'>
shape (2, 3)
dimension - 2
dtype int64

data -
 [[1 2 3]
 [4 5 6]]


In [91]:
ary_transpose = ary.T
aryinfo(ary_transpose)

type <class 'numpy.ndarray'>
shape (3, 2)
dimension - 2
dtype int64

data -
 [[1 4]
 [2 5]
 [3 6]]


In [94]:
vec = np.arange(10)
aryinfo(vec)

print()
print('1차원 배열에 대한 전치연산은 가능할까? - ' , vec.T)
print('안된다...그런데 방법이 있을까? - ')# 2차원으로 바꿔버리고 뒤집어 버리기~
print()

vec_transpose = vec.reshape(1, 10 ).T
aryinfo(vec_transpose)

type <class 'numpy.ndarray'>
shape (10,)
dimension - 1
dtype int64

data -
 [0 1 2 3 4 5 6 7 8 9]

1차원 배열에 대한 전치연산은 가능할까? -  [0 1 2 3 4 5 6 7 8 9]
안된다...그런데 방법이 있을까? - 

type <class 'numpy.ndarray'>
shape (10, 1)
dimension - 2
dtype int64

data -
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


#### 다차원 배열을 1차원으로 만들어야 한다면????
- flatten()

In [97]:
vec_transpose.flatten()
# 차원에 대한 주의가 필요하다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
ary = np.arange(10)
aryinfo(ary.reshape(1,10))
aryinfo(ary.reshape(10,1))

print()
print("reshape이 아닌 차원증가를 위해서는 :new axis를 사용함")

aryinfo(ary[:,np.newaxis])
aryinfo(ary[np.newaxis,:])

type <class 'numpy.ndarray'>
shape (1, 10)
dimension - 2
dtype int64

data -
 [[0 1 2 3 4 5 6 7 8 9]]
type <class 'numpy.ndarray'>
shape (10, 1)
dimension - 2
dtype int64

data -
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

reshape이 아닌 차원증가를 위해서는 :new axis를 사용함
type <class 'numpy.ndarray'>
shape (10, 1)
dimension - 2
dtype int64

data -
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
type <class 'numpy.ndarray'>
shape (1, 10)
dimension - 2
dtype int64

data -
 [[0 1 2 3 4 5 6 7 8 9]]


- ndarray(배열) 모든 원소에 대해서 순차적으로 접근해야 한다면???
- iternext(), finished

In [108]:
ary = np.arange(10)
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
for tmp in ary:
  print(tmp, end="\t")
  

0	1	2	3	4	5	6	7	8	9	

In [116]:
print("1차원 ndarray에 대한 iterator- ")


ite = np.nditer(ary, flags = ["c_index"])

while not ite.finished:
  idx = ite.index
  print("idx", idx, ary[idx])
  ite.iternext()


1차원 ndarray에 대한 iterator- 
idx 0 0
idx 1 1
idx 2 2
idx 3 3
idx 4 4
idx 5 5
idx 6 6
idx 7 7
idx 8 8
idx 9 9


In [117]:
ary_reshape = ary.reshape(2,5)
ary_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [118]:
print('shape - ' , ary_reshape.shape)
print('row   - ' , ary_reshape.shape[0])
print('col   - ' , ary_reshape.shape[1])

shape -  (2, 5)
row   -  2
col   -  5


In [133]:
for row in range(ary_reshape.shape[0]):
  for col in range(ary_reshape.shape[1]):
    print(ary_reshape[row][col], end = "\t")
  print()

print()

#for문으로 돌려도 되는데 
#while 끝나기전까지 주구장창 돈다라고 하면
# 끝까지 돌고 나와서 확인함.
ite = np.nditer(ary_reshape, flags = ["multi_index"])
while not ite.finished:
  idx = ite.multi_index
  print(ary_reshape[idx], idx ,end="\t")
  ite.iternext()

0	1	2	3	4	
5	6	7	8	9	

0 (0, 0)	1 (0, 1)	2 (0, 2)	3 (0, 3)	4 (0, 4)	5 (1, 0)	6 (1, 1)	7 (1, 2)	8 (1, 3)	9 (1, 4)	

SyntaxError: ignored