<a href="https://colab.research.google.com/github/Yeunseok97/Data-analysis_machine_learning/blob/main/Numpy_review2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
def aryinfo(ary):
    print("type-", type(ary))
    print("shape-", ary.shape)
    print("dimension -", ary.ndim)
    print("dtype -", ary.dtype)
    print()
    print("data -", ary)

In [4]:
ary = np.arange(0,12,1)
aryinfo(ary)

type- <class 'numpy.ndarray'>
shape- (12,)
dimension - 1
dtype - int64

data - [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
ary_reshape = ary.reshape(-1,4)
aryinfo(ary_reshape)

type- <class 'numpy.ndarray'>
shape- (3, 4)
dimension - 2
dtype - int64

data - [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
ary_reshape = ary.reshape(2,2,3)
aryinfo(ary_reshape)

type- <class 'numpy.ndarray'>
shape- (2, 2, 3)
dimension - 3
dtype - int64

data - [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


#### 배열 병합(연결)
hstack vstack, dstack, stack, r_[], c_[], tile


In [ ]:
print("hstack")
print("행의 수가 같아야함.")

In [14]:
ary_one = np.ones((2,2))
print(ary_one)

ary_zeros = np.zeros((2,3))
print(ary_zeros)

hstack = np.hstack([ary_one, ary_zeros])
print(hstack)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]


In [ ]:
print("vstack")
print("열의 수가 같아야함.")

In [20]:
ary_one = np.ones((3,3))
ary_zeros = np.zeros((1,3))
vstack = np.vstack([ary_one, ary_zeros])
print(vstack)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]


In [21]:
print("dstack")
print("열과 행이 모두 같아야 깊이 탐색이 된다.")



dstack
열과 행이 모두 같아야 깊이 탐색이 된다.


In [25]:
ary_one = np.ones((3,3))
ary_zeros = np.zeros((3,3))
dstack = np.dstack([ary_one, ary_zeros])
print(dstack)

[[[1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]]]


In [26]:
aryinfo(np.r_[np.array([1,2,3]), np.array([4,5,6])])

type- <class 'numpy.ndarray'>
shape- (6,)
dimension - 1
dtype - int64

data - [1 2 3 4 5 6]


In [31]:
aryinfo(np.c_[np.array([1,2,3]),np.array([4,5,6])])

type- <class 'numpy.ndarray'>
shape- (3, 2)
dimension - 2
dtype - int64

data - [[1 4]
 [2 5]
 [3 6]]


In [32]:
print("tile = 동일한 배열을 반복해서 연결- 마지막 () 왼쪽놈이 행 다음놈이 열")

tile = 동일한 배열을 반복해서 연결- 마지막 () 왼쪽놈이 행 다음놈이 열


In [36]:
aryinfo(np.tile(np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]]),(2,2,2)))

type- <class 'numpy.ndarray'>
shape- (4, 4, 6)
dimension - 3
dtype - int64

data - [[[ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]
  [ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]]

 [[ 6  7  8  6  7  8]
  [ 9 10 11  9 10 11]
  [ 6  7  8  6  7  8]
  [ 9 10 11  9 10 11]]

 [[ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]
  [ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]]

 [[ 6  7  8  6  7  8]
  [ 9 10 11  9 10 11]
  [ 6  7  8  6  7  8]
  [ 9 10 11  9 10 11]]]


In [ ]:
# 위 결과가 나올 수 있도록 함수를 이용하여 작성해 보세요~~~
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],

#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])


In [43]:
ary_zeros = np.zeros((3,3))
ary_ones = np.ones((3,2))
a = np.arange(10,151,10)
b = a.reshape(3,5)
print(b)

ary_hstack = np.hstack([ary_zeros, ary_ones])
print(ary_hstack)
ary_vstack = np.vstack([ary_hstack,b])
print()
print(ary_vstack)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


#### delete function


In [44]:
ary = np.random.randint(0,10,(3,4))
aryinfo(ary)

type- <class 'numpy.ndarray'>
shape- (3, 4)
dimension - 2
dtype - int64

data - [[5 4 4 7]
 [2 8 5 4]
 [1 7 8 5]]


In [47]:
ary_delete = np.delete(ary, 2, axis = 1)
aryinfo(ary_delete)

type- <class 'numpy.ndarray'>
shape- (3, 3)
dimension - 2
dtype - int64

data - [[5 4 7]
 [2 8 4]
 [1 7 5]]


#### 배열의 연산

In [48]:
%%time 
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = np.zeros_like(x)

for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: user 7.55 ms, sys: 0 ns, total: 7.55 ms
Wall time: 9.56 ms


In [51]:
print("비교연산")
tmpX = np.array([1,2,3,4])
tmpY = np.array([5,2,6,4])
tmpZ = np.array([1,2,3,4])

print(tmpX ==tmpY )
print(tmpX >=tmpY )

print(np.all(tmpX==tmpY))

비교연산
[False  True False  True]
[False  True False  True]
False


In [55]:
ary = np.arange(10)
print("벡터연산 - ", ary * 10)

벡터연산 -  [ 0 10 20 30 40 50 60 70 80 90]


In [57]:
ary = np.arange(12).reshape(3,4)
print(ary*100)

[[   0  100  200  300]
 [ 400  500  600  700]
 [ 800  900 1000 1100]]


In [58]:
X = np.vstack([range(7)[idx:idx+3]for idx in range(5)])
print(X)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [62]:
X = np.vstack([range(7)[idx: idx+3] for idx in range(5)])
print(X)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [66]:
y = np.arange(5).reshape(1,5)
print(y)




[[0 1 2 3 4]]


#### 차원축소 연산
- min, max
- argmin, argmax -> 
- sum, min

In [69]:
X = np.array([1,2,3,4,5])
print("vector value- ",X)

vector value-  [1 2 3 4 5]


In [70]:
print("sum-", np.sum(X))
print("sum-", X.sum())

sum- 15
sum- 15


In [74]:
print("min -", X.min())
print(np.min(X))

print("max-", np.max(X))
print("max -", X.max())

min - 1
1
max- 5
max - 5


In [76]:
print("argmin -index")
print("min -",np.argmin(X))
print("min -", X.argmin())

argmin -index
min - 0
min - 0


In [77]:
print("argmax -index")
print("max -", np.argmax(X))
print("max -", X.argmax())

argmax -index
max - 4
max - 4


In [78]:
print("mean -")
print("max -", np.mean(X))
print("max -", X.mean())

mean -
max - 3.0
max - 3.0


In [79]:
print()
print("median -", np.median(X))


median - 3.0


In [83]:
ary_zero = np.zeros((3,3))

In [84]:
np.any(ary_zero!=0)

False

In [85]:
np.all(ary_zero ==ary_zero)

True

- 만약 연산의 대상이 2차원 행렬이면?
- axis 축의 방향을 설정해야한다.

In [86]:
ary = np.arange(1, 21, 1).reshape(4, -1)
ary

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
ary = np.arange(1,21,1).reshape(4,-1)
print(ary)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [91]:
print("matrix sum()")
print("matrix sum-", np.sum(ary, axis = 0))
print("열방향의 sum")
print()

matrix sum()
matrix sum- [34 38 42 46 50]
열방향의 sum



In [94]:
print("matrix argmax -", ary.sum(axis = 1))
print("행방향의 sum")

matrix argmax - [15 40 65 90]
행방향의 sum


In [98]:
print("arming - index ")
print("matrix argmax-", np.argmax(ary, axis = 1))
print("matrix sum -", ary.sum(axis=1))

arming - index 
matrix argmax- [4 4 4 4]
matrix sum - [15 40 65 90]


In [99]:
print("argmin - index")
print("matrix argmin-", np.argmin(ary, axis = 1))
print("matrix argmax-", np.argmax(ary, axis = 1))

argmin - index
matrix argmin- [0 0 0 0]
matrix argmax- [4 4 4 4]


In [101]:
ary = np.random.randint(1, 10000000, (5,6))
ary

array([[9494228, 7917330, 2327358,   76044, 8563521, 8273253],
       [2342544, 2046889, 1299664, 4455871, 8376591, 3743701],
       [1333702, 6436722, 1003924, 3033377, 7392705, 7548654],
       [2176332, 3345650, 4454157, 1220968,  728213, 2633859],
       [4362528,  206516, 9059232, 6306608, 5195668, 5131577]])

In [128]:
#ary shape[i]는 행인지 열인지에 대한 인덱스임

np.hstack([ary[idx].sum() for idx in range(ary.shape[0])])
np.hstack([ary[idx].max() for idx in range(ary.shape[0])])
np.hstack([ary[:, idx].mean() for idx in range(ary.shape[0])])
np.hstack([ary[:, idx].min() for idx in range(ary.shape[0])])
np.hstack([ary[:, idx].max() for idx in range(ary.shape[0])])

array([9494228, 7917330, 9059232, 6306608, 8563521])

In [129]:
ary = np.random.randint(0,17, (4,4))
ary

array([[13, 12, 12,  7],
       [11, 12, 14, 10],
       [ 4, 14, 10,  9],
       [ 4,  6,  3, 13]])

In [130]:
#행기준
np.sort(ary, axis =1)

array([[ 7, 12, 12, 13],
       [10, 11, 12, 14],
       [ 4,  9, 10, 14],
       [ 3,  4,  6, 13]])

In [131]:
#열기준
print(np.sort(ary, axis =0))

[[ 4  6  3  7]
 [ 4 12 10  9]
 [11 12 12 10]
 [13 14 14 13]]


In [132]:
ary = np.array([4,3,5,7])
ary

array([4, 3, 5, 7])

In [133]:
print("정렬된 인덱스를 필요로 한다면")
idx = np.argsort(ary)
idx

정렬된 인덱스를 필요로 한다면


array([1, 0, 2, 3])

In [134]:
ary[idx]

array([3, 4, 5, 7])

In [135]:
print("matrix sort-")
ary = np.random.randint(0, 17, (4,4))
ary

matrix sort-


array([[ 1, 12, 13,  3],
       [15, 14,  4,  1],
       [ 0,  7,  1,  0],
       [ 7, 12, 13,  9]])

In [136]:
ary[0].argsort()

array([0, 3, 1, 2])

In [137]:
ary_row = np.array([7,8,9])
ary_row

array([7, 8, 9])

In [138]:
ary_new = np.concatenate(ary,)

In [139]:
ary_row.reshape(1,3)

array([[7, 8, 9]])